### ISSUE TITLE
topic: Dev User Experience Revisit

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-python#324]
- [ ] Config should be possible to omit, enable one-liner to access and query
- [x] Getting Started docs should be straightforward, via #323 
- [x] Should be possible to render/vis any result with ease(like render FIND PATH/MATCH path/GET SUBGRAPH result is HARD), via #323 
- [x] Should be easy to have results as pandas dataframe, via #323 
- [ ] Should be easy to prepare query param, instead of handling raw types to be passed, https://github.com/vesoft-inc/nebula-python/issues/273
- [x] Handling of reconnection/timeout etc., via #306 
- [ ] fully typed
- [x] modern package management, via PDM

**Comment by wey-gu** [comment]
cc @Nicole00 @HarrisChu @haoxins
